<?php

/**
 * Podium installation steps.
 * v0.2
 * @author Paweł Bizley Brzozowski <pawel@positive.codes>
 */

use yii\db\Schema;

return [
    [
        'table'  => 'log',
        'call'   => 'createTable',
        'schema' => [
            'id'       => Schema::TYPE_BIGPK,
            'level'    => Schema::TYPE_INTEGER,
            'category' => Schema::TYPE_STRING,
            'log_time' => Schema::TYPE_DOUBLE,
            'ip'       => Schema::TYPE_STRING . '(20)',
            'message'  => Schema::TYPE_TEXT,
            'model'    => Schema::TYPE_INTEGER,
            'user'     => Schema::TYPE_INTEGER,
        ],
    ],
    [
        'table' => 'log',
        'call'  => 'addIndex',
        'name'  => 'level',
        'cols'  => ['level'],
    ],
    [
        'table' => 'log',
        'call'  => 'addIndex',
        'name'  => 'category',
        'cols'  => ['category'],
    ],
    [
        'table' => 'log',
        'call'  => 'addIndex',
        'name'  => 'model',
        'cols'  => ['model'],
    ],
    [
        'table' => 'log',
        'call'  => 'addIndex',
        'name'  => 'user',
        'cols'  => ['user'],
    ],
    [
        'table'  => 'config',
        'call'   => 'createTable',
        'schema' => [
            'name'  => Schema::TYPE_STRING . ' NOT NULL',
            'value' => Schema::TYPE_STRING . ' NOT NULL',
            'PRIMARY KEY (name)',
        ],
    ],
    [
        'table' => 'config',
        'call'  => 'addConfig',
    ],
    [
        'table'  => 'category',
        'call'   => 'createTable',
        'schema' => [
            'id'          => Schema::TYPE_PK,
            'name'        => Schema::TYPE_STRING . ' NOT NULL',
            'slug'        => Schema::TYPE_STRING . ' NOT NULL',
            'keywords'    => Schema::TYPE_STRING,
            'description' => Schema::TYPE_STRING,
            'visible'     => Schema::TYPE_SMALLINT . ' NOT NULL DEFAULT 1',
            'sort'        => Schema::TYPE_SMALLINT . ' NOT NULL DEFAULT 0',
            'created_at'  => Schema::TYPE_INTEGER . ' NOT NULL',
            'updated_at'  => Schema::TYPE_INTEGER . ' NOT NULL',
        ],
    ],
    [
        'table' => 'category',
        'call'  => 'addIndex',
        'name'  => 'sort',
        'cols'  => ['sort', 'id'],
    ],
    [
        'table' => 'category',
        'call'  => 'addIndex',
        'name'  => 'name',
        'cols'  => ['name'],
    ],
    [
        'table' => 'category',
        'call'  => 'addIndex',
        'name'  => 'display',
        'cols'  => ['id', 'slug'],
    ],
    [
        'table' => 'category',
        'call'  => 'addIndex',
        'name'  => 'display_guest',
        'cols'  => ['id', 'slug', 'visible'],
    ],
    [
        'table'  => 'forum',
        'call'   => 'createTable',
        'schema' => [
            'id'          => Schema::TYPE_PK,
            'category_id' => Schema::TYPE_INTEGER . ' NOT NULL',
            'name'        => Schema::TYPE_STRING . ' NOT NULL',
            'sub'         => Schema::TYPE_STRING,
            'slug'        => Schema::TYPE_STRING . ' NOT NULL',
            'keywords'    => Schema::TYPE_STRING,
            'description' => Schema::TYPE_STRING,
            'visible'     => Schema::TYPE_SMALLINT . ' NOT NULL DEFAULT 1',
            'sort'        => Schema::TYPE_SMALLINT . ' NOT NULL DEFAULT 0',
            'threads'     => Schema::TYPE_INTEGER . ' NOT NULL DEFAULT 0',
            'posts'       => Schema::TYPE_INTEGER . ' NOT NULL DEFAULT 0',
            'created_at'  => Schema::TYPE_INTEGER . ' NOT NULL',
            'updated_at'  => Schema::TYPE_INTEGER . ' NOT NULL',
        ],
    ],
    [
        'table' => 'forum',
        'call'  => 'addIndex',
        'name'  => 'sort',
        'cols'  => ['sort', 'id'],
    ],
    [
        'table' => 'forum',
        'call'  => 'addIndex',
        'name'  => 'name',
        'cols'  => ['name'],
    ],
    [
        'table' => 'forum',
        'call'  => 'addIndex',
        'name'  => 'display',
        'cols'  => ['id', 'category_id'],
    ],
    [
        'table' => 'forum',
        'call'  => 'addIndex',
        'name'  => 'display_slug',
        'cols'  => ['id', 'category_id', 'slug'],
    ],
    [
        'table' => 'forum',
        'call'  => 'addIndex',
        'name'  => 'display_guest_slug',
        'cols'  => ['id', 'category_id', 'slug', 'visible'],
    ],
    [
        'table'  => 'forum',
        'call'   => 'addForeign',
        'key'    => 'category_id',
        'ref'    => 'category',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'thread',
        'call'   => 'createTable',
        'schema' => [
            'id'             => Schema::TYPE_PK,
            'name'           => Schema::TYPE_STRING . ' NOT NULL',
            'slug'           => Schema::TYPE_STRING . ' NOT NULL',
            'category_id'    => Schema::TYPE_INTEGER . ' NOT NULL',
            'forum_id'       => Schema::TYPE_INTEGER . ' NOT NULL',
            'author_id'      => Schema::TYPE_INTEGER . ' NOT NULL',
            'pinned'         => Schema::TYPE_SMALLINT . ' NOT NULL DEFAULT 0',
            'locked'         => Schema::TYPE_SMALLINT . ' NOT NULL DEFAULT 0',
            'posts'          => Schema::TYPE_INTEGER . ' NOT NULL DEFAULT 0',
            'views'          => Schema::TYPE_INTEGER . ' NOT NULL DEFAULT 0',
            'created_at'     => Schema::TYPE_INTEGER . ' NOT NULL',
            'updated_at'     => Schema::TYPE_INTEGER . ' NOT NULL',
            'new_post_at'    => Schema::TYPE_INTEGER . ' NOT NULL DEFAULT 0',
            'edited_post_at' => Schema::TYPE_INTEGER . ' NOT NULL DEFAULT 0',
        ],
    ],
    [
        'table' => 'thread',
        'call'  => 'addIndex',
        'name'  => 'name',
        'cols'  => ['name'],
    ],
    [
        'table' => 'thread',
        'call'  => 'addIndex',
        'name'  => 'created_at',
        'cols'  => ['created_at'],
    ],
    [
        'table' => 'thread',
        'call'  => 'addIndex',
        'name'  => 'display',
        'cols'  => ['id', 'category_id', 'forum_id'],
    ],
    [
        'table' => 'thread',
        'call'  => 'addIndex',
        'name'  => 'display_slug',
        'cols'  => ['id', 'category_id', 'forum_id', 'slug'],
    ],
    [
        'table' => 'thread',
        'call'  => 'addIndex',
        'name'  => 'sort',
        'cols'  => ['pinned', 'updated_at', 'id'],
    ],
    [
        'table' => 'thread',
        'call'  => 'addIndex',
        'name'  => 'sort_author',
        'cols'  => ['updated_at', 'id'],
    ],
    [
        'table'  => 'thread',
        'call'   => 'addForeign',
        'key'    => 'category_id',
        'ref'    => 'category',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'thread',
        'call'   => 'addForeign',
        'key'    => 'forum_id',
        'ref'    => 'forum',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'post',
        'call'   => 'createTable',
        'schema' => [
            'id'         => Schema::TYPE_PK,
            'content'    => Schema::TYPE_TEXT . ' NOT NULL',
            'thread_id'  => Schema::TYPE_INTEGER . ' NOT NULL',
            'forum_id'   => Schema::TYPE_INTEGER . ' NOT NULL',
            'author_id'  => Schema::TYPE_INTEGER . ' NOT NULL',
            'edited'     => Schema::TYPE_SMALLINT . ' NOT NULL DEFAULT 0',
            'likes'      => Schema::TYPE_SMALLINT . ' NOT NULL DEFAULT 0',
            'dislikes'   => Schema::TYPE_SMALLINT . ' NOT NULL DEFAULT 0',
            'created_at' => Schema::TYPE_INTEGER . ' NOT NULL',
            'updated_at' => Schema::TYPE_INTEGER . ' NOT NULL',
            'edited_at'  => Schema::TYPE_INTEGER . ' NOT NULL DEFAULT 0',
        ],
    ],
    [
        'table' => 'post',
        'call'  => 'addIndex',
        'name'  => 'updated_at',
        'cols'  => ['updated_at'],
    ],
    [
        'table' => 'post',
        'call'  => 'addIndex',
        'name'  => 'created_at',
        'cols'  => ['created_at'],
    ],
    [
        'table' => 'post',
        'call'  => 'addIndex',
        'name'  => 'edited_at',
        'cols'  => ['edited_at'],
    ],
    [
        'table' => 'post',
        'call'  => 'addIndex',
        'name'  => 'identify',
        'cols'  => ['id', 'thread_id', 'forum_id'],
    ],
    [
        'table'  => 'post',
        'call'   => 'addForeign',
        'key'    => 'thread_id',
        'ref'    => 'thread',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'post',
        'call'   => 'addForeign',
        'key'    => 'forum_id',
        'ref'    => 'forum',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'vocabulary',
        'call'   => 'createTable',
        'schema' => [
            'id'   => Schema::TYPE_PK,
            'word' => Schema::TYPE_STRING . ' NOT NULL',
        ],
    ],
    [
        'table' => 'vocabulary',
        'call'  => 'addIndex',
        'name'  => 'word',
        'cols'  => ['word'],
    ],
    [
        'table'  => 'vocabulary_junction',
        'call'   => 'createTable',
        'schema' => [
            'id'      => Schema::TYPE_PK,
            'word_id' => Schema::TYPE_INTEGER . ' NOT NULL',
            'post_id' => Schema::TYPE_INTEGER . ' NOT NULL',
        ],
    ],
    [
        'table'  => 'vocabulary_junction',
        'call'   => 'addForeign',
        'key'    => 'word_id',
        'ref'    => 'vocabulary',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'vocabulary_junction',
        'call'   => 'addForeign',
        'key'    => 'post_id',
        'ref'    => 'post',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'auth_rule',
        'call'   => 'createTable',
        'schema' => [
            'name'       => Schema::TYPE_STRING . '(64) NOT NULL',
            'data'       => Schema::TYPE_TEXT,
            'created_at' => Schema::TYPE_INTEGER,
            'updated_at' => Schema::TYPE_INTEGER,
            'PRIMARY KEY (name)',
        ],
    ],
    [
        'table'  => 'auth_item',
        'call'   => 'createTable',
        'schema' => [
            'name'        => Schema::TYPE_STRING . '(64) NOT NULL',
            'type'        => Schema::TYPE_INTEGER . ' NOT NULL',
            'description' => Schema::TYPE_TEXT,
            'rule_name'   => Schema::TYPE_STRING . '(64)',
            'data'        => Schema::TYPE_TEXT,
            'created_at'  => Schema::TYPE_INTEGER,
            'updated_at'  => Schema::TYPE_INTEGER,
            'PRIMARY KEY (name)',
        ],
    ],
    [
        'table'  => 'auth_item',
        'call'   => 'addForeign',
        'key'    => 'rule_name',
        'ref'    => 'auth_rule',
        'col'    => 'name',
        'delete' => 'SET NULL',
        'update' => 'CASCADE',
    ],
    [
        'table' => 'auth_item',
        'call'  => 'addIndex',
        'name'  => 'type',
        'cols'  => ['type'],
    ],
    [
        'table'  => 'auth_item_child',
        'call'   => 'createTable',
        'schema' => [
            'parent' => Schema::TYPE_STRING . '(64) NOT NULL',
            'child'  => Schema::TYPE_STRING . '(64) NOT NULL',
            'PRIMARY KEY (parent, child)',
        ],
    ],
    [
        'table'  => 'auth_item_child',
        'call'   => 'addForeign',
        'key'    => 'parent',
        'ref'    => 'auth_item',
        'col'    => 'name',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'auth_item_child',
        'call'   => 'addForeign',
        'key'    => 'child',
        'ref'    => 'auth_item',
        'col'    => 'name',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'auth_assignment',
        'call'   => 'createTable',
        'schema' => [
            'item_name'  => Schema::TYPE_STRING . '(64) NOT NULL',
            'user_id'    => Schema::TYPE_STRING . '(64) NOT NULL',
            'created_at' => Schema::TYPE_INTEGER,
            'PRIMARY KEY (item_name, user_id)',
        ],
    ],
    [
        'table'  => 'auth_assignment',
        'call'   => 'addForeign',
        'key'    => 'item_name',
        'ref'    => 'auth_item',
        'col'    => 'name',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table' => 'auth_rule',
        'call'  => 'addRules',
    ],
    [
        'table'  => 'user',
        'call'   => 'createTable',
        'schema' => [
            'id'                   => Schema::TYPE_PK,
            'inherited_id'         => Schema::TYPE_INTEGER . ' NOT NULL DEFAULT 0',
            'username'             => Schema::TYPE_STRING,
            'slug'                 => Schema::TYPE_STRING . ' NOT NULL',
            'auth_key'             => Schema::TYPE_STRING . '(32)',
            'password_hash'        => Schema::TYPE_STRING,
            'password_reset_token' => Schema::TYPE_STRING,
            'activation_token'     => Schema::TYPE_STRING,
            'email_token'          => Schema::TYPE_STRING,
            'email'                => Schema::TYPE_STRING,
            'new_email'            => Schema::TYPE_STRING,
            'anonymous'            => Schema::TYPE_SMALLINT . ' NOT NULL DEFAULT 0',
            'status'               => Schema::TYPE_SMALLINT . ' NOT NULL DEFAULT 1',
            'role'                 => Schema::TYPE_SMALLINT . ' NOT NULL DEFAULT 1',
            'timezone'             => Schema::TYPE_STRING . '(45)',
            'created_at'           => Schema::TYPE_INTEGER . ' NOT NULL',
            'updated_at'           => Schema::TYPE_INTEGER . ' NOT NULL',
        ],
    ],
    [
        'table' => 'user',
        'call'  => 'addIndex',
        'name'  => 'username',
        'cols'  => ['username'],
    ],
    [
        'table' => 'user',
        'call'  => 'addIndex',
        'name'  => 'status',
        'cols'  => ['status'],
    ],
    [
        'table' => 'user',
        'call'  => 'addIndex',
        'name'  => 'role',
        'cols'  => ['role'],
    ],
    [
        'table' => 'user',
        'call'  => 'addIndex',
        'name'  => 'email',
        'cols'  => ['email'],
    ],
    [
        'table' => 'user',
        'call'  => 'addIndex',
        'name'  => 'mod',
        'cols'  => ['status', 'role'],
    ],
    [
        'table' => 'user',
        'call'  => 'addIndex',
        'name'  => 'find_email',
        'cols'  => ['status', 'email'],
    ],
    [
        'table' => 'user',
        'call'  => 'addIndex',
        'name'  => 'find_username',
        'cols'  => ['status', 'username'],
    ],
    [
        'table' => 'user',
        'call'  => 'addIndex',
        'name'  => 'password_reset_token',
        'cols'  => ['password_reset_token'],
    ],
    [
        'table' => 'user',
        'call'  => 'addIndex',
        'name'  => 'activation_token',
        'cols'  => ['activation_token'],
    ],
    [
        'table' => 'user',
        'call'  => 'addIndex',
        'name'  => 'email_token',
        'cols'  => ['email_token'],
    ],
    [
        'table'  => 'user_meta',
        'call'   => 'createTable',
        'schema' => [
            'id'         => Schema::TYPE_PK,
            'user_id'    => Schema::TYPE_INTEGER . ' NOT NULL',
            'location'   => Schema::TYPE_STRING . '(32) NOT NULL',
            'signature'  => Schema::TYPE_STRING . '(512) NOT NULL',
            'gravatar'   => Schema::TYPE_SMALLINT . ' NOT NULL DEFAULT 0',
            'avatar'     => Schema::TYPE_STRING,
            'created_at' => Schema::TYPE_INTEGER . ' NOT NULL',
            'updated_at' => Schema::TYPE_INTEGER . ' NOT NULL',
        ],
    ],
    [
        'table'  => 'user_meta',
        'call'   => 'addForeign',
        'key'    => 'user_id',
        'ref'    => 'user',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'user_ignore',
        'call'   => 'createTable',
        'schema' => [
            'id'         => Schema::TYPE_PK,
            'user_id'    => Schema::TYPE_INTEGER . ' NOT NULL',
            'ignored_id' => Schema::TYPE_INTEGER . ' NOT NULL',
        ],
    ],
    [
        'table'  => 'user_ignore',
        'call'   => 'addForeign',
        'key'    => 'user_id',
        'ref'    => 'user',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'user_ignore',
        'call'   => 'addForeign',
        'key'    => 'ignored_id',
        'ref'    => 'user',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'user_friend',
        'call'   => 'createTable',
        'schema' => [
            'id'        => Schema::TYPE_PK,
            'user_id'   => Schema::TYPE_INTEGER . ' NOT NULL',
            'friend_id' => Schema::TYPE_INTEGER . ' NOT NULL',
        ],
    ],
    [
        'table'  => 'user_friend',
        'call'   => 'addForeign',
        'key'    => 'user_id',
        'ref'    => 'user',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'user_friend',
        'call'   => 'addForeign',
        'key'    => 'friend_id',
        'ref'    => 'user',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'user_activity',
        'call'   => 'createTable',
        'schema' => [
            'id'         => Schema::TYPE_PK,
            'user_id'    => Schema::TYPE_INTEGER,
            'username'   => Schema::TYPE_STRING,
            'user_slug'  => Schema::TYPE_STRING,
            'user_role'  => Schema::TYPE_INTEGER,
            'url'        => Schema::TYPE_STRING . '(1024) NOT NULL',
            'ip'         => Schema::TYPE_STRING . '(15)',
            'anonymous'  => Schema::TYPE_SMALLINT . ' NOT NULL DEFAULT 0',
            'created_at' => Schema::TYPE_INTEGER . ' NOT NULL',
            'updated_at' => Schema::TYPE_INTEGER . ' NOT NULL',
        ],
    ],
    [
        'table' => 'user_activity',
        'call'  => 'addIndex',
        'name'  => 'updated_at',
        'cols'  => ['updated_at'],
    ],
    [
        'table' => 'user_activity',
        'call'  => 'addIndex',
        'name'  => 'url',
        'cols'  => ['url'],
    ],
    [
        'table' => 'user_activity',
        'call'  => 'addIndex',
        'name'  => 'members',
        'cols'  => ['updated_at', 'user_id', 'anonymous'],
    ],
    [
        'table' => 'user_activity',
        'call'  => 'addIndex',
        'name'  => 'guests',
        'cols'  => ['updated_at', 'user_id'],
    ],
    [
        'table'  => 'user_activity',
        'call'   => 'addForeign',
        'key'    => 'user_id',
        'ref'    => 'user',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'message',
        'call'   => 'createTable',
        'schema' => [
            'id'              => Schema::TYPE_PK,
            'sender_id'       => Schema::TYPE_INTEGER . ' NOT NULL',
            'topic'           => Schema::TYPE_STRING . ' NOT NULL',
            'content'         => Schema::TYPE_TEXT . ' NOT NULL',
            'sender_status'   => Schema::TYPE_SMALLINT . ' NOT NULL DEFAULT 1',
            'replyto'         => Schema::TYPE_INTEGER . ' NOT NULL DEFAULT 0',
            'created_at'      => Schema::TYPE_INTEGER . ' NOT NULL',
            'updated_at'      => Schema::TYPE_INTEGER . ' NOT NULL',
        ],
    ],
    [
        'table' => 'message',
        'call'  => 'addIndex',
        'name'  => 'topic',
        'cols'  => ['topic'],
    ],
    [
        'table' => 'message',
        'call'  => 'addIndex',
        'name'  => 'replyto',
        'cols'  => ['replyto'],
    ],
    [
        'table' => 'message',
        'call'  => 'addIndex',
        'name'  => 'sent',
        'cols'  => ['sender_id', 'sender_status'],
    ],
    [
        'table'  => 'message',
        'call'   => 'addForeign',
        'key'    => 'sender_id',
        'ref'    => 'user',
        'col'    => 'id',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'message_receiver',
        'call'   => 'createTable',
        'schema' => [
            'id'              => Schema::TYPE_PK,
            'message_id'      => Schema::TYPE_INTEGER . ' NOT NULL',
            'receiver_id'     => Schema::TYPE_INTEGER . ' NOT NULL',
            'receiver_status' => Schema::TYPE_SMALLINT . ' NOT NULL DEFAULT 1',
            'created_at'      => Schema::TYPE_INTEGER . ' NOT NULL',
            'updated_at'      => Schema::TYPE_INTEGER . ' NOT NULL',
        ],
    ],
    [
        'table' => 'message_receiver',
        'call'  => 'addIndex',
        'name'  => 'inbox',
        'cols'  => ['receiver_id', 'receiver_status'],
    ],
    [
        'table'  => 'message_receiver',
        'call'   => 'addForeign',
        'key'    => 'message_id',
        'ref'    => 'message',
        'col'    => 'id',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'message_receiver',
        'call'   => 'addForeign',
        'key'    => 'receiver_id',
        'ref'    => 'user',
        'col'    => 'id',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'email',
        'call'   => 'createTable',
        'schema' => [
            'id'         => Schema::TYPE_PK,
            'user_id'    => Schema::TYPE_INTEGER,
            'email'      => Schema::TYPE_STRING . ' NOT NULL',
            'subject'    => Schema::TYPE_TEXT . ' NOT NULL',
            'content'    => Schema::TYPE_TEXT . ' NOT NULL',
            'status'     => Schema::TYPE_SMALLINT . ' NOT NULL DEFAULT 0',
            'attempt'    => Schema::TYPE_SMALLINT . ' NOT NULL DEFAULT 0',
            'created_at' => Schema::TYPE_INTEGER . ' NOT NULL',
            'updated_at' => Schema::TYPE_INTEGER . ' NOT NULL',
        ],
    ],
    [
        'table' => 'email',
        'call'  => 'addIndex',
        'name'  => 'status',
        'cols'  => ['status'],
    ],
    [
        'table'  => 'email',
        'call'   => 'addForeign',
        'key'    => 'user_id',
        'ref'    => 'user',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'thread_view',
        'call'   => 'createTable',
        'schema' => [
            'id'               => Schema::TYPE_PK,
            'user_id'          => Schema::TYPE_INTEGER . ' NOT NULL',
            'thread_id'        => Schema::TYPE_INTEGER . ' NOT NULL',
            'new_last_seen'    => Schema::TYPE_INTEGER . ' NOT NULL',
            'edited_last_seen' => Schema::TYPE_INTEGER . ' NOT NULL',
        ],
    ],
    [
        'table'  => 'thread_view',
        'call'   => 'addForeign',
        'key'    => 'user_id',
        'ref'    => 'user',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'thread_view',
        'call'   => 'addForeign',
        'key'    => 'thread_id',
        'ref'    => 'thread',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'post_thumb',
        'call'   => 'createTable',
        'schema' => [
            'id'         => Schema::TYPE_PK,
            'user_id'    => Schema::TYPE_INTEGER . ' NOT NULL',
            'post_id'    => Schema::TYPE_INTEGER . ' NOT NULL',
            'thumb'      => Schema::TYPE_SMALLINT . ' NOT NULL',
            'created_at' => Schema::TYPE_INTEGER . ' NOT NULL',
            'updated_at' => Schema::TYPE_INTEGER . ' NOT NULL',
        ],
    ],
    [
        'table'  => 'post_thumb',
        'call'   => 'addForeign',
        'key'    => 'user_id',
        'ref'    => 'user',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'post_thumb',
        'call'   => 'addForeign',
        'key'    => 'post_id',
        'ref'    => 'post',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'subscription',
        'call'   => 'createTable',
        'schema' => [
            'id'        => Schema::TYPE_PK,
            'user_id'   => Schema::TYPE_INTEGER . ' NOT NULL',
            'thread_id' => Schema::TYPE_INTEGER . ' NOT NULL',
            'post_seen' => Schema::TYPE_SMALLINT . ' NOT NULL DEFAULT 1',
        ],
    ],
    [
        'table'  => 'subscription',
        'call'   => 'addForeign',
        'key'    => 'user_id',
        'ref'    => 'user',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'subscription',
        'call'   => 'addForeign',
        'key'    => 'thread_id',
        'ref'    => 'thread',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'   => 'moderator',
        'call'    => 'createTable',
        'schema' => [
            'id'       => Schema::TYPE_PK,
            'user_id'  => Schema::TYPE_INTEGER . ' NOT NULL',
            'forum_id' => Schema::TYPE_INTEGER . ' NOT NULL',
        ],
    ],
    [
        'table'  => 'moderator',
        'call'   => 'addForeign',
        'key'    => 'user_id',
        'ref'    => 'user',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'moderator',
        'call'   => 'addForeign',
        'key'    => 'forum_id',
        'ref'    => 'forum',
        'col'    => 'id',
        'delete' => 'CASCADE',
        'update' => 'CASCADE',
    ],
    [
        'table'  => 'content',
        'call'   => 'createTable',
        'schema' => [
            'id'      => Schema::TYPE_PK,
            'name'    => Schema::TYPE_STRING . ' NOT NULL',
            'topic'   => Schema::TYPE_STRING . ' NOT NULL',
            'content' => Schema::TYPE_TEXT . ' NOT NULL',
        ],
    ],
    [
        'table' => 'content',
        'call'  => 'addContent',
    ],
    [
        'table' => 'user',
        'call'  => 'addAdmin',
    ],
];