<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access roles have been created.' => 'アクセスロールが作成されました。',
    'Administrator account has been created.' => '管理者アカウントが作成されました。',
    'Administrator privileges have been set for the user of ID {id}.' => '{id} IDのユーザーに対して管理者権限が設定されている',
    'All unread threads have been marked as seen.' => 'すべての未読スレッドにはマークが付けられています。',
    'Are you trying to move posts from this thread to this very same thread?' => 'このスレッドの投稿をこの同じスレッドに移動しようとしていますか？',
    'Cache has been cleared.' => 'キャッシュがクリアされました。',
    'Cannot find inherited user of given ID. No administrator privileges have been set.' => '指定されたIDの継承されたユーザーを見つけることができません。 管理者権限が設定されていません。',
    'Category has been deleted.' => 'カテゴリが削除されました。',
    'Category has been updated.' => 'カテゴリが更新されました。',
    'Config setting {name} has been updated to {value}.' => '構成設定{name}が{value}に更新されました。',
    'Content has been saved.' => 'コンテンツが保存されました。',
    'Default Config settings have been added.' => 'デフォルトの設定が追加されました。',
    'Default Content has been added.' => 'デフォルトのコンテンツが追加されました。',
    'Error during access roles creating' => 'アクセスロールの作成中にエラーが発生しました',
    'Error during account creating' => 'アカウント作成中のエラー',
    'Error during configuration updating' => '構成の更新中のエラー',
    'Error during content adding' => 'コンテンツ追加中のエラー',
    'Error during settings adding' => '設定の追加中にエラーが発生しました',
    'Error during table column {name} adding' => 'テーブル列{name}の追加中にエラーが発生しました',
    'Error during table column {name} dropping' => 'テーブル列{name}が削除中にエラーが発生しました',
    'Error during table column {name} renaming to {new}' => 'テーブル列{name}中のエラーが{new}に変更されました',
    'Error during table column {name} updating' => 'テーブル列{name}の更新中にエラーが発生しました',
    'Error during table foreign key {name} adding' => 'テーブルの外部キー{name}の追加中にエラーが発生しました',
    'Error during table foreign key {name} dropping' => 'テーブルの外部キー{name}が削除中にエラーが発生しました',
    'Error during table index {name} adding' => 'テーブルインデックス{name}の追加中にエラーが発生しました',
    'Error during table index {name} dropping' => 'テーブルインデックス{name}の削除中にエラーが発生しました',
    'Error during table {name} creating' => 'テーブル{name}の作成中にエラーが発生しました',
    'Error during table {name} dropping' => 'テーブル{name}の削除中にエラーが発生しました',
    'Error during table {name} renaming to {new}' => 'テーブル{name}中のエラーが{new}に変更されました',
    'Error while checking current database version! Please verify your database.' => '現在のデータベースのバージョンを確認中にエラーが発生しました。 データベースを確認してください。',
    'Forum has been deleted.' => 'フォーラムが削除されました。',
    'Forum has been updated.' => 'フォーラムが更新されました。',
    'Hey! Your new forum account has just been automatically created! Go to {link} to complement it.' => 'ねえ！ 新しいフォーラムアカウントが自動的に作成されました！ {link}に行きましょう。',
    'If you want to move posts to a new thread you have to enter its name and select parent forum.' => '投稿を新しいスレッドに移動するには、名前を入力して親フォーラムを選択する必要があります。',
    'Installation aborted! Can not find the requested drop step.' => 'インストールがキャンセルされました！ 要求されたドロップステップが見つかりません。',
    'Installation aborted! Can not find the requested installation step.' => 'インストール中止！ 要求されたインストール手順が見つかりません。',
    'Installation aborted! Column name missing.' => 'インストール中止！ 列名がありません。',
    'Installation aborted! Column type missing.' => 'インストール中止！ 列のタイプがありません。',
    'Installation aborted! Column value missing.' => 'インストール中止！ 列の値がありません。',
    'Installation aborted! Database schema missing.' => 'インストール中止！ データベーススキーマが見つかりません。',
    'Installation aborted! Foreign key name missing.' => 'インストール中止！ 外部キー名がありません。',
    'Installation aborted! Foreign key reference missing.' => 'インストール中止！ 外部キー参照がありません。',
    'Installation aborted! Index columns missing.' => 'インストール中止！ インデックス列がありません。',
    'Installation aborted! Index name missing.' => 'インストール中止！ インデックス名がありません。',
    'Installation aborted! New column name missing.' => 'インストール中止！ 新しい列名がありません。',
    'Installation aborted! New table name missing.' => 'インストール中止！ 新しいテーブル名がありません。',
    'Installation aborted! Referenced columns missing.' => 'インストール中止！ 参照された列がありません。',
    'It looks like there is a new version of Podium database! {link}' => 'Podiumデータベースの新しいバージョンがあるようです。 {link}',
    'Login' => 'ログイン',
    'Maintenance page' => 'メンテナンスページ',
    'Message has been deleted.' => 'メッセージは削除されました。',
    'Message has been sent.' => 'メッセージが送信されました。',
    'Moderation list has been saved.' => '管理リストが保存されました。',
    'Moderation list has been updated.' => 'モデレーションリストが更新されました。',
    'Module and database versions are the same!' => 'モジュールとデータベースのバージョンは同じです！',
    'Module version appears to be older than database! Please verify your database.' => 'モジュールのバージョンがデータベースより古いと思われます。 データベースを確認してください。',
    'New category has been created.' => '新しいカテゴリが作成されました。',
    'New forum has been created.' => '新しいフォーラムが作成されました。',
    'New reply has been added.' => '新しい返信が追加されました。',
    'New thread has been created.' => '新しいスレッドが作成されました。',
    'No administrator privileges have been set!' => '管理者権限が設定されていません！',
];
